subscribers:
  - name: 'client-1'
    id_file: './id_rsa1.pub'
    hotkey: False
  - name: 'client-2'
    id_file: './id_rsa2.pub'
    hotkey: 'f8'
  - name: 'local'
    hotkey: False
hotkeys:
  switch: 'f7'
  exit: 'f3'
devices:
  - 'YSPRINGTECH USB OPTICAL MOUSE'
  - 'SINO WEALTH Gaming KB  Keyboard'
  - 'SINO WEALTH Gaming KB '
