subscribers:
  - name: 'local'
    hotkey: False
  # - name: 'client-1'
  #   id_file: 'path/to/key1.pub'
  #   hotkey: False
  # - name: 'client-2'
  #   id_file: 'path/to/key2.pub'
  #   hotkey: 'f8'
hotkeys:
  switch: 'f7'
  exit: 'f3'
devices:
  - 'YSPRINGTECH USB OPTICAL MOUSE'
  - 'SINO WEALTH Gaming KB  Keyboard'
  - 'SINO WEALTH Gaming KB '
